name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Toolchain
        run: sudo apt install -y gcc-aarch64-linux-gnu make bc

      - name: Build Kernel
        run: |
          cd kernel
          make ARCH=arm64 O=out defconfig
          make -j$(nproc) ARCH=arm64 O=out Image.gz-dtb

      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: kernel/out/Image.gz-dtb
