name: Build Kernel

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu make bc git

      - name: Build kernel
        run: |
          cd kernel
          make ARCH=arm64 O=out defconfig
          make -j$(nproc) ARCH=arm64 O=out Image.gz-dtb

      - name: Upload kernel
        uses: actions/upload-artifact@v3
        with:
          name: kernel
          path: kernel/out/Image.gz-dtb
