name: Build boot.img

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: kernel
          path: kernel
      - uses: actions/download-artifact@v3
        with:
          name: rootfs
          path: rootfs

      - name: Build boot.img
        run: |
          bash bootimg/mkbootimg.sh

      - name: Upload boot.img
        uses: actions/upload-artifact@v3
        with:
          name: bootimg
          path: K5Pro_Linux_boot.img
